services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: secret123
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
