services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"   # API MinIO
      - "9001:9001"   # Console web MinIO
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./data:/data   # Persistência local de dados MinIO
    command: server /data --console-address ":9001"
